### ISSUE TITLE
Installer stuck: netplugin failed with no error message

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/snc#203] opened 2020-07-06 07:48 UTC
Sometimes when running snc, the cluster doesn't progress anymore and around 5-10 containers are waiting in the state "ContainerCreating".

Looking at logs, they are all waiting for a network. 
``` 
crc-8tfgf-master-0 crio[1425]: time="2020-07-06 07:41:06.471577450Z" level=error msg="Error while adding pod to CNI network \"multus-cni-network\": netplugin failed with no error message"
``` 

I had to restart all pods in openshift-sdn namespace to unlock everything. Sadly, these containers don't report any errors in their logs.

**Comment by guillaumerose** [comment] 2020-07-06 11:07
```
Events:
  Type     Reason                  Age        From                         Message
  ----     ------                  ----       ----                         -------
  Normal   Scheduled               <unknown>  default-scheduler            Successfully assigned openshift-marketplace/marketplace-operator-7d858b7747-7fc48 to crc-p4sm2-master-0
  Warning  FailedCreatePodSandBox  16m        kubelet, crc-p4sm2-master-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_marketplace-operator-7d858b7747-7fc48_openshift-marketplace_54657dca-e0c1-4d1e-a991-4b726b7042c7_0(cccb1387ee48090b9bb2b9ca9879642cb09ffbc46a1e552157c2bbb2e09deb83): netplugin failed with no error message
  Warning  FailedCreatePodSandBox  13m        kubelet, crc-p4sm2-master-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_marketplace-operator-7d858b7747-7fc48_openshift-marketplace_54657dca-e0c1-4d1e-a991-4b726b7042c7_0(d7ecbb199c93c47aac5d82fb6e382a3a533dad9d2cc628d62eda9e6fa66d592f): netplugin failed with no error message
  Warning  FailedCreatePodSandBox  9m49s      kubelet, crc-p4sm2-master-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_marketplace-operator-7d858b7747-7fc48_openshift-marketplace_54657dca-e0c1-4d1e-a991-4b726b7042c7_0(2232c7d9706a5a4abb4771c934e8245507929ec2d7e51fb50be6c9be87570c0a): netplugin failed with no error message
  Warning  FailedCreatePodSandBox  6m38s      kubelet, crc-p4sm2-master-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_marketplace-operator-7d858b7747-7fc48_openshift-marketplace_54657dca-e0c1-4d1e-a991-4b726b7042c7_0(629c6a96a2373d61f990a0a2d7b3787d99fd210246601ae68ed10cdad35c6d7a): netplugin failed with no error message
  Warning  FailedCreatePodSandBox  4m3s       kubelet, crc-p4sm2-master-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_marketplace-operator-7d858b7747-7fc48_openshift-marketplace_54657dca-e0c1-4d1e-a991-4b726b7042c7_0(1aa6a2c681df4b6c45ca5ae523042a0d6258e509a02b2d0d0443103e5c3184c5): netplugin failed with no error message
  Normal   AddedInterface          3m46s      multus                       Add eth0 [10.128.0.94/23]
  Normal   Pulling                 3m45s      kubelet, crc-p4sm2-master-0  Pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:643978bd7cfc6056aad9c0c8be01962987d85324ff3275a6baa1263a1a4bcf26"
  Normal   Pulled                  2m50s      kubelet, crc-p4sm2-master-0  Successfully pulled image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:643978bd7cfc6056aad9c0c8be01962987d85324ff3275a6baa1263a1a4bcf26"
  Normal   Created                 2m49s      kubelet, crc-p4sm2-master-0  Created container marketplace-operator
  Normal   Started                 2m49s      kubelet, crc-p4sm2-master-0  Started container marketplace-operator
``` 

About 13min stuck.

**Comment by guillaumerose** [comment] 2020-07-06 11:12
In the ovs pod in openshift-sdn namespace:

``` 
2020-07-06T10:58:05.863Z|00024|jsonrpc|WARN|unix#1080: send error: Broken pipe
2020-07-06T10:58:05.863Z|00025|reconnect|WARN|unix#1080: connection dropped (Broken pipe)
2020-07-06T11:01:25.520Z|00217|bridge|WARN|could not open network device veth86d28bf4 (No such device)
2020-07-06T11:01:25.544Z|00218|bridge|WARN|could not open network device vethc7bbd048 (No such device)
2020-07-06T11:01:25.571Z|00219|bridge|WARN|could not open network device vethea3a4197 (No such device)
2020-07-06T11:01:25.600Z|00220|bridge|WARN|could not open network device veth136237a3 (No such device)
2020-07-06T11:01:25.627Z|00221|bridge|WARN|could not open network device veth5b07b5c5 (No such device)
2020-07-06T11:01:25.657Z|00222|bridge|WARN|could not open network device vethaec2ac98 (No such device)
2020-07-06T11:01:25.687Z|00223|bridge|WARN|could not open network device vethbdbb5504 (No such device)
```

**Comment by bbrowning** [comment] 2020-07-06 12:41
https://bugzilla.redhat.com/show_bug.cgi?id=1817464 and https://bugzilla.redhat.com/show_bug.cgi?id=1811140 seem related here. The former was marked as a duplicate of the latter, and the latter links to a couple of GitHub PRs that seem to indicate this is fixed in recent 4.4.x and later releases. If the version of OpenShift you're using with snc here has those fixes, perhaps there's another related issue still lingering.

**Comment by guillaumerose** [comment] 2020-07-06 12:42
I'm using 4.5.0-rc.6

**Comment by bbrowning** [comment] 2020-07-06 12:46
I've seen this on 4.5.0-rc.1, 4.5.0-rc.2, and 4.4.8 as well. I did not hit this on 4.5.0-rc.4 for whatever reason - probably just luck with some race condition that triggers it.

**Comment by ratripathi** [comment] 2021-01-25 22:10
I am seeing this on OCP 4.6.9 as well:

```
Jan 25 16:45:10.211610 worker2.example.com crio[1847]: time="2021-01-25 16:45:10.209171978Z" level=error msg="Error adding network: netplugin failed with no error message: signal: killed"
Jan 25 16:45:10.211610 worker2.example.com crio[1847]: time="2021-01-25 16:45:10.209230420Z" level=error msg="Error while adding pod to CNI network \"multus-cni-network\": netplugin failed with no error message: signal: killed"
Jan 25 16:45:10.211610 worker2.example.com crio[1847]: time="2021-01-25 16:45:10.211266207Z" level=error msg="Error deleting network: netplugin failed with no error message: context deadline exceeded"
Jan 25 16:45:10.211610 worker2.example.com crio[1847]: time="2021-01-25 16:45:10.211283467Z" level=error msg="Error while removing pod from CNI network \"multus-cni-network\": netplugin failed with no error message: context deadline exceeded"
```

**Comment by praveenkumar** [comment] 2021-06-07 12:19
closing this since not happening in 4.7 or even with 4.8 versions.

**Closed by praveenkumar** 2021-06-07 12:19 UTC
